const { app, BrowserWindow, WebContentsView } = require('electron')
const fs=require('fs'),path=require('path')
const LOG=path.resolve(__dirname,'..','docs','hostwin-test.log')
const P=`(() => ({vw:innerWidth,vh:innerHeight,vis:document.visibilityState,ta:document.querySelectorAll('textarea').length,login:document.querySelectorAll('form[action*="login"]').length}))()`
fs.writeFileSync(LOG,'start\n','utf8'); const T0=Date.now()
const log=(m,e)=>fs.appendFileSync(LOG,`[+${((Date.now()-T0)/1000).toFixed(1)}s] ${m} ${JSON.stringify(e)}\n`,'utf8')
process.on('uncaughtException',e=>log('UNCAUGHT '+(e&&e.stack||e)))
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms))
const probe=async(tag,v)=>log(tag,{dom:await v.webContents.executeJavaScript(P,true).catch(e=>({err:e.message}))})
app.whenReady().then(async()=>{
  log('ready')
  const host=new BrowserWindow({width:1280,height:900,x:-4000,y:-4000,show:false,skipTaskbar:true})
  const main=new BrowserWindow({width:1280,height:860,show:true})
  await sleep(800)
  const v=new WebContentsView({webPreferences:{partition:'persist:torra-chatgpt',contextIsolation:true,sandbox:true}})
  v.setBounds({x:0,y:0,width:1280,height:900}); host.contentView.addChildView(v)
  v.webContents.setBackgroundThrottling(false)
  v.webContents.loadURL('https://chatgpt.com/')
  await sleep(15000); await probe('1) hidden host',v)
  host.contentView.removeChildView(v); v.setBounds({x:64,y:56,width:900,height:700}); main.contentView.addChildView(v)
  await sleep(4000); await probe('2) moved to main',v)
  main.contentView.removeChildView(v); v.setBounds({x:0,y:0,width:1280,height:900}); host.contentView.addChildView(v)
  await sleep(6000); await probe('3) back to host',v)
  app.exit(0)
})
